version: '3.8'

services:
    proxy:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - backend

    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        command: php artisan queue:work
        networks:
            - backend

    db:
        image: postgres:latest
        restart: unless-stopped
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - backend

    redis:
        image: redis:alpine
        restart: unless-stopped
        volumes:
            - redis_data:/data:cached
        networks:
            - backend
networks:
    backend:

volumes:
    db_data:
    redis_data:
